//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 10:18:25 AM PDT 
//


package com.microsoft.azurebatch.jenkins;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for assembliesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assembliesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="assembly" type="{}assemblyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="assemblies")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assembliesType", propOrder = {
    "assembly"
})
public class AssembliesType {

    @XmlElement(required = true)
    protected AssemblyType assembly;

    /**
     * Gets the value of the assembly property.
     * 
     * @return
     *     possible object is
     *     {@link AssemblyType }
     *     
     */
    public AssemblyType getAssembly() {
        return assembly;
    }

    /**
     * Sets the value of the assembly property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssemblyType }
     *     
     */
    public void setAssembly(AssemblyType value) {
        this.assembly = value;
    }

}
