//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.30 at 01:47:30 PM PDT 
//


package com.microsoft.azurebatch.jenkins;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.microsoft.azurebatch.jenkins package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TasksDescription_QNAME = new QName("", "TasksDescription");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.microsoft.azurebatch.jenkins
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TasksDescriptionType }
     * 
     */
    public TasksDescriptionType createTasksDescriptionType() {
        return new TasksDescriptionType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link TaskGroupType }
     * 
     */
    public TaskGroupType createTaskGroupType() {
        return new TaskGroupType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TasksDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TasksDescription")
    public JAXBElement<TasksDescriptionType> createTasksDescription(TasksDescriptionType value) {
        return new JAXBElement<TasksDescriptionType>(_TasksDescription_QNAME, TasksDescriptionType.class, null, value);
    }

}
